[project]
name = "aitt-symbol-clf"
version = "0.1.0"
description = "Train a Half-Circle grayscale image classifier using pytorch"
authors = [
    { name = "Alexandre Poupeau", email = "contact@alexandrepoupeau.com" }
]
readme = "README.md"
requires-python = ">=3.12,<3.15"
dependencies= [
    "fastapi[standard] (>=0.128.0,<0.129.0)",
    "torch (>=2.10.0,<3.0.0)",
    "torchvision (>=0.25.0,<0.26.0)",
]

[dependency-groups]
dev = [
    "opencv-python (>=4.13.0.90,<5.0.0.0)",
    "pymupdf (>=1.26.7,<2.0.0)",
    "tqdm (>=4.67.2,<5.0.0)",
    "torchmetrics (>=1.8.2,<2.0.0)",
    "matplotlib (>=3.10.8,<4.0.0)",
    "scikit-learn (>=1.8.0,<2.0.0)",
    "tensorboard (>=2.20.0,<3.0.0)",
    "jupyter (>=1.1.1,<2.0.0)",
    "notebook (>=7.5.3,<8.0.0)"
]

[tool.poetry]
requires-poetry = ">=2.0"
package-mode = false
